domains 
disease,indication,name=symbol
predicates 
hypothesis(name,disease) 
symptom(name,indication)
clauses 
symptom(ali,fever). 
symptom(ali,rash). 
symptom(ali,headache). 
symptom(ali,runny_nose). 
hypothesis(Patient,german_measles):-
symptom(Patient,fever), 
symptom(Patient,headache), 
symptom(Patient,runny_nose), 
symptom(Patient,rash). 
hypothesis(Patient,flu):-
symptom(Patient,fever), 
symptom(Patient,headache), 
symptom(Patient,body_ache), 
symptom(Patient,cough).
