trace 
domains 
person,hobby=symbol 
predicates 
likes(person,hobby)
clauses 
clearwindow. 
likes(pooja,music). 
likes(rina,dancing). 
likes(ali,swimming). 
likes(jagruti,reading). 
likes(jalpa,travelling). 
likes(tejashwini,study). 
likes(jay,playing). 
likes(bhargav,comedy). 
likes(vicky,playing). 
likes(sam,shopping).
